# Generated by Mongoose Wizard - Makefile for Windows, Mac, Linux
# Environment setup: https://mongoose.ws/documentation/tutorials/tools/

SOURCES = main.c sens.c $(wildcard mongoose/*.c)
CFLAGS = -W -Wall -Wextra -Werror -Wundef -Wshadow -g3 -Os -I. -Imongoose
CFLAGS += -Wno-cast-function-type
MFLAGS = -DMG_DATA_SIZE=64 -DMG_ENABLE_PACKED_FS=1 -DMG_TLS=MG_TLS_BUILTIN

# Build program from sources
build: $(SOURCES)
	$(CC) $(SOURCES) $(CFLAGS) $(MFLAGS) $(CFLAGS_EXTRA) -o firmware
	cp firmware firmware.bin

windows: $(PROG)
	cl /MD /Os /W3 /nologo $(SOURCES) $(MFLAGS) $(CFLAGS_EXTRA) /Fefirmware.exe
	copy firmware.exe firmware.bin

run:
	nodemon --exec "make && ./firmware || true" -w . -e c,h
