// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Default mock implementation of the API callbacks

#include "mongoose_glue.h"
static struct data s_data = {30.5, 25.5, 10};
void glue_get_data(struct data *data) {
  *data = s_data;  // Sync with your device
}

static struct enable s_enable = {false, false, false};
void glue_get_enable(struct enable *data) {
  *data = s_enable;  // Sync with your device
}
void glue_set_enable(struct enable *data) {
  s_enable = *data; // Sync with your device
}
